apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: {{ .Release.Name }}-postgres-app
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: {{ .Release.Name }}-postgres-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-app
    spec:
      containers:
      - name: {{ .Release.Name }}-postgres-container
        image: ghcr.io/dcsaorg/dcsa-information-model:latest
        env: 
        - name: POSTGRES_PASSWORD
          value: "change_this_password"
        volumeMounts:
        - name: my-store
          mountPath: /mystore
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      volumes:
        - name: my-store
