apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dcsajit-service
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip      
    alb.ingress.kubernetes.io/healthcheck-path: /ovs/v3/actuator/health
  labels:
    app: {{ .Release.Name }}-dcsajit-app
spec:
  ports:
  - name: dcsajit
    port: 9090
    targetPort: dcsajit
  selector:
    app: {{ .Release.Name }}-dcsajit-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dcsajit-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-dcsajit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dcsajit-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dcsajit-app
    spec:
      containers:
      - name: {{ .Release.Name }}-dcsajit-container
        image: ghcr.io/dcsaorg/dcsa-ovs:apvcv-583-set-url-prefix-ac0b3d2
        env:
        - name: db_hostname
          value: {{ .Values.db.host }}
        - name: DCSA_URL_PREFIX
          value: "/ovs"
        ports:
        - name: dcsajit
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /ovs/v3/actuator/health
            port: 9090
          initialDelaySeconds: 200
          periodSeconds: 50           
        volumeMounts:
          - name: {{ .Release.Name }}-dcsacfgvol
            mountPath: /config/dcsa-config.yaml
            subPath: dcsa-config.yaml
      volumes:
        - name: {{ .Release.Name }}-dcsacfgvol
          configMap:
            name: {{ .Release.Name }}-configmap
            defaultMode: 0777
            items:
              - key: dcsa-config.yaml
                path: dcsa-config.yaml
---
