apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dcsap6-service
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
  labels:
    app: {{ .Release.Name }}-dcsap6-app
spec:
  ports:
  - name: dcsap6
    port: 80
    targetPort: dcsap6
  selector:
    app: {{ .Release.Name }}-dcsap6-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dcsap6-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-dcsap6-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dcsap6-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dcsap6-app
    spec:
      containers:
      - name: {{ .Release.Name }}-dcsap6-container
        image: ghcr.io/dcsaorg/dcsa-p6-ui:v1.2.0-beta1-rc2
        env:
        ports:
        - name: dcsap6
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
        volumeMounts:
        - name: {{ .Release.Name }}-configmap
          mountPath: /usr/share/nginx/html/assets/config.json
          subPath: config.json
      volumes:
        - name: {{ .Release.Name }}-configmap
          configMap:
            name: {{ .Release.Name }}-configmap
            defaultMode: 0777
            items:
              - key: config.json
                path: config.json

