name: Publish

on:
  push:
    branches: [ provider-tck ]

env:
  awsaccountid: '012254934199'
  awsregion: 'eu-west-1'
  baseurl: 'p6-kaohsiung-development.dcsa.org'
  hostedzoneid: 'Z096510526PM9TJX9FNQM'
  helmversion: '0.1.88'
  dockerImageTag: 'live-dev'
  helmChartName: 'dcsasandboxhamburg'
  ingressChartName: 'dcsaingresscluster'
  deploydb: 'true'
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    env:
      awsaccesskeyid: ${{ secrets.KAOHSIUNG_AWSACCESSKEYID }}
      awssecretaccesskey: ${{ secrets.KAOHSIUNG_AWSSECRETACCESSKEY }}
    steps:
      - name: Checkout the infrastructure code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ env.awsaccesskeyid }}
          aws-secret-access-key: ${{ env.awssecretaccesskey }}
          aws-region:  ${{ env.awsregion }}

      - name: Creating secret
        run: |
          aws secretsmanager create-secret --name DBPassword --secret-string ${{env.dbpassword}} || true
          aws secretsmanager update-secret --secret-id DBPassword --secret-string ${{env.dbpassword}} || true
      - name: CDK Bootstrapping AWS Account
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'bootstrap'
          cdk_args: '--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess'
          cdk_stack: 'aws://${{ env.awsaccountid }}/${{ env.awsregion }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.awsaccesskeyid }}
          AWS_SECRET_ACCESS_KEY: ${{ env.awssecretaccesskey }}
          PARTICIPANTS:  ${{ env.participants }}
          AWS_DEFAULT_REGION: ${{ env.awsregion }}
          BASEURL: ''
          HOSTEDZONEID: ''
          EXPERIMENTAL: ''

      - name: Deploying the CDK Cluster Code
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'st'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ env.awsaccesskeyid }}
          AWS_SECRET_ACCESS_KEY: ${{ env.awssecretaccesskey }}
          PARTICIPANTS:  ${{ env.participants }}
          AWS_DEFAULT_REGION: ${{ env.awsregion }}
          BASEURL: ${{ env.baseurl }}
          HOSTEDZONEID: ${{ env.hostedzoneid }}
          HELMVERSION: ${{ env.helmversion }}

      - name: HELM
        run: |
          #!/usr/bin/env bash
          # Ensure the script is executable in case it was edited on windows
          script="./shell-scripts/deploy-application.sh"
          chmod a+x $script && $script
        env:
          DB_USER: postgres
          DB_PASSWORD: ${{env.dbpassword}}
          PARTICIPANTS:  ${{ env.participants }}
          BASEURL: ${{ env.baseurl }}
        #  SMTPPASSWORD: ${{ env.smtppassword }}
        #  SMTPUSERNAME: ${{ env.smtpusername }}
          DOCKERIMAGETAG: ${{ env.dockerImageTag }}
          HELMCHARTNAME: ${{ env.helmChartName }}
      - name: HELM 2
        run: |
          #!/usr/bin/env bash
          # Ensure the script is executable in case it was edited on windows
          script="./shell-scripts/deploy-ingressalb.sh"
          chmod a+x $script && $script
        env:
          DB_USER: postgres
          DB_PASSWORD: ${{env.dbpassword}}
          PARTICIPANTS:  ${{ env.participants }}
          BASEURL: ${{ env.baseurl }}
          SMTPPASSWORD: ${{ env.smtppassword }}
          SMTPUSERNAME: ${{ env.smtpusername }}
          COGNITOAPPCLIENTID: ${{ env.cognitoappclientid }}
          COGNITOUSERPOOLID: ${{ env.cognitouserpoolid }}
          DOCKERIMAGETAG: ${{ env.dockerImageTag }}
          INGRESSCHARTNAME: ${{ env.ingressChartName }}
      - name: Updating load balancer dns
        run: |
          sleep 3m
          alburl=$(aws elbv2 describe-load-balancers | grep "DNSName" | xargs | cut -d' ' -f2 | cut -d',' -f1)
          echo $alburl
          cat ${{ env.participantsfile }} | jq -c '.[]' | while read i; do
           carrierinternal=$(echo $i | jq -c '.name' | tr -d '"')
           echo $carrierinternal
           carrierurl="$carrierinternal.$carrierbaseurl"
           echo $carrierurl
           cp ./route53/route53.json ./participantroute.json
           sed -i "s#mydns#$alburl#g" ./participantroute.json
           sed -i "s#carrierurl#$carrierurl#g" ./participantroute.json
           cat ./participantroute.json
           aws route53 change-resource-record-sets --hosted-zone-id ${{ env.hostedzoneid }} --change-batch file://./participantroute.json
          done
        env:
          carrierbaseurl: ${{ env.baseurl }}
