name: Publish

on:
  push:
    branches: [ hamburgtest ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the infrastructure code
        uses: actions/checkout@v2
      - name: CDK Bootstrapping AWS Account
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'bootstrap'
          cdk_args: '--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess'
          cdk_stack: 'aws://853169102957/eu-west-1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HAMBURGTESTAWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HAMBURGTESTAWSSECRETACCESSKEY }}
          PARTICIPANTS:  ${{ secrets.HAMBURGDEVPARTICIPANTS }}
          AWS_DEFAULT_REGION: 'eu-west-1'
          BASEURL: 'p6-hamburg-test.dcsa.org'
          HOSTEDZONEID: 'Z0356896WKOUB3ZK0XRN'
      - name: Deploying the CDK Code
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'st'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HAMBURGTESTAWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HAMBURGTESTAWSSECRETACCESSKEY }}
          PARTICIPANTS:  ${{ secrets.HAMBURGPRODPARTICIPANTS }}
          AWS_DEFAULT_REGION: 'eu-west-1'
          BASEURL: 'p6-hamburg-test.dcsa.org'
          HOSTEDZONEID: 'Z0356896WKOUB3ZK0XRN'
          COGNITOAPPCLIENTID: "2id9n1me4q5pn6412r6dtamgul"
          COGNITOUSERPOOLID: "eu-west-1_UV95TORKw"
          HELMVERSION: "0.1.46"
          SMTPUSERNAME: "AKIARP6MS7EFTHTJMPBM"
          SMTPPASSWORD: ${{ secrets.HAMBURGPRODSMTPPASSWORD }}
      - name: Updating load balancer dns
        run: |
          sleep 3m
          aws elbv2 describe-load-balancers
          alburl=$(aws elbv2 describe-load-balancers | grep "DNSName" | xargs | cut -d' ' -f2 | cut -d',' -f1)
          echo $alburl
          sed -i "s#mydns#$alburl#g" ./route53/route53.json
          cat ./route53/route53.json
          aws route53 change-resource-record-sets --hosted-zone-id Z0356896WKOUB3ZK0XRN --change-batch file://./route53/route53.json

                 
